name: flutter_template
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ## Icons
  cupertino_icons: ^1.0.6

  ## Other
  get: ^4.6.6
  flutter_localization: ^0.2.0
  flutter_secure_storage: ^9.1.1
  jwt_decoder: ^2.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - asset/
